[package]
name = "lmap"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.83"
hostname = "0.4.0"
hwlocality = { git = "https://github.com/HadrienG2/hwlocality", features = ["hwloc-2_5_0"] }
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
